### ISSUE TITLE
我用其他语言写的抢票软件，但是验证验证码的时候总是返回0

### ISSUE THREAD

**Issue by coretimes** [sjfkai/grab12306#1]
我用其他语言写的抢票软件，但是验证验证码的时候总是返回0，我都是浏览器截包的，应该没问题的，cookie都是浏览器一样4个cookie，但是验证验证码的时候就是失败永远返回{"validateMessagesShowId":"_validatorMessage","status":true,"httpstatus":200,"data":{"result":"0","msg":""},"messages":[],"validateMessages":{}}
困扰很久了，请问知道这是什么原因吗？

**Comment by sjfkai** [comment]
@coretimes  不好意思没有研究过12306的验证码

**Comment by coretimes** [comment]
@sjfkai  跟验证码没关系呀，我的意思是我就是手动点击的验证码，然后提交验证就返回那个结果，点的正确的验证码，也是返回0
