### ISSUE TITLE
列车时刻表抓取出错

### ISSUE THREAD

**Issue by miaomiaokang** [sjfkai/grab12306#6]
具体信息如下：
info: 正在抓取车次：D2198(汉口-->宁波)   175/8653
error: request error 将尝试再次抓取 12306的数据为:undefined
info: 正在抓取车次：D2205(成都-->上海虹桥)   176/8653
error: request error 将尝试再次抓取 12306的数据为:undefined
info: 正在抓取车次：D2206(上海虹桥-->成都)   177/8653
error: request error 将尝试再次抓取 12306的数据为:undefined
info: 正在抓取车次：D2207(上海虹桥-->成都)   178/8653

**Comment by sjfkai** [comment]
我试了一下应该是没问题的  `request error` 请检查自己的网络有没有问题。或者自己的网络能否正常访问`12306`。

**Comment by miaomiaokang** [comment]
@sjfkai 检查了下，可以联网，浏览器可以访问12306，可以获取车站和车次，就是不能获取时刻表

**Comment by sjfkai** [comment]
![image](https://user-images.githubusercontent.com/7581901/30798398-1c8e537e-a20c-11e7-8766-e5d6f3b4af1f.png)

抓取时刻表用的是这个接口，在你本机上试一下吧。



https://kyfw.12306.cn/otn/czxx/queryByTrainNo?train_no=240000G5610G&from_station_telecode=BXP&to_station_telecode=SJP&depart_date=2017-09-25

**Comment by miaomiaokang** [comment]
![1](https://user-images.githubusercontent.com/32059798/30798569-b6cfcf76-a20c-11e7-97b9-b3ee49c49d22.png)
这样的么？

**Comment by miaomiaokang** [comment]
@sjfkai 你给的这个网址我也能得到结果哦
{"validateMessagesShowId":"_validatorMessage","status":true,"httpstatus":200,"data":{"data":[{"start_station_name":"北京西","arrive_time":"----","station_train_code":"G561","station_name":"北京西","train_class_name":"高速","service_type":"1","start_time":"16:53","stopover_time":"----","end_station_name":"郑州东","station_no":"01","isEnabled":true},{"arrive_time":"17:34","station_name":"保定东","start_time":"17:36","stopover_time":"2分钟","station_no":"02","isEnabled":true},{"arrive_time":"18:12","station_name":"石家庄","start_time":"18:15","stopover_time":"3分钟","station_no":"03","isEnabled":true},{"arrive_time":"18:45","station_name":"邢台东","start_time":"18:47","stopover_time":"2分钟","station_no":"04","isEnabled":false},{"arrive_time":"19:04","station_name":"邯郸东","start_time":"19:06","stopover_time":"2分钟","station_no":"05","isEnabled":false},{"arrive_time":"19:23","station_name":"安阳东","start_time":"19:25","stopover_time":"2分钟","station_no":"06","isEnabled":false},{"arrive_time":"19:51","station_name":"新乡东","start_time":"19:53","stopover_time":"2分钟","station_no":"07","isEnabled":false},{"arrive_time":"20:14","station_name":"郑州东","start_time":"20:14","stopover_time":"----","station_no":"08","isEnabled":false}]},"messages":[],"validateMessages":{}}

**Comment by sjfkai** [comment]
是抓取每一趟车次都报
`error: request error 将尝试再次抓取 12306的数据为:undefined` 错误吗？

还是抓取一段时间以后才报的？ 

如果只是几个报错的话不用在意，这些报错的都会记录下来，在结束前重新抓取。

**Comment by miaomiaokang** [comment]
@sjfkai 从“正在抓取车次列表”开始所有的都是这样，我跟了一下，好像是parse JSON的时候出错了呢

**Comment by miaomiaokang** [comment]
好像是parse JSON的时候出错了呢

**Comment by sjfkai** [comment]
返回的数据是`undefined `导致`parse JSON`出错了。你可以打印一下`url`看看有没有问题

**Comment by miaomiaokang** [comment]
@sjfkai 
info: https://kyfw.12306.cn/otn/czxx/queryByTrainNo?train_no=2400000D410H&from_station_telecode=BJP&to_station_telecode=DFT&depart_date=2017-09-25
error: request error0 将尝试再次抓取 12306的数据为:undefined
info: 正在抓取车次：D42(大连北-->北京)   38/8563
info: https://kyfw.12306.cn/otn/czxx/queryByTrainNo?train_no=1g00000D3906&from_station_telecode=DFT&to_station_telecode=BJP&depart_date=2017-09-25
error: request error0 将尝试再次抓取 12306的数据为:undefined
info: 正在抓取车次：D43(大连北-->北京)   39/8563
info: https://kyfw.12306.cn/otn/czxx/queryByTrainNo?train_no=1g00000D430D&from_station_telecode=DFT&to_station_telecode=BJP&depart_date=2017-09-25
error: request error0 将尝试再次抓取 12306的数据为:undefined
info: 正在抓取车次：D44(北京-->大连北)   40/8563
info: https://kyfw.12306.cn/otn/czxx/queryByTrainNo?train_no=2400000D450D&from_station_telecode=BJP&to_station_telecode=DFT&depart_date=2017-09-25
error: request error0 将尝试再次抓取 12306的数据为:undefined
info: 正在抓取车次：D45(北京-->大连北)   41/8563
info: https://kyfw.12306.cn/otn/czxx/queryByTrainNo?train_no=2400000D450D&from_station_telecode=BJP&to_station_telecode=DFT&depart_date=2017-09-25
error: request error0 将尝试再次抓取 12306的数据为:undefined

试了，这些数据应该都可以返回

			try {
				data = JSON.parse(res[1]);
			} catch (error) {
				logger.info(url);
				logger.error("request error0 将尝试再次抓取 12306的数据为:" + res[1]);
				errorList.push(train);
				return Promise.resolve();
			}

代码里返回的res貌似很复杂，不是下面的结构啊：{"validateMessagesShowId":"_validatorMessage","status":true,"httpstatus":200,"data":{"data":[{"start_station_name":"北京西","arrive_time":"----","station_train_code":"G561","station_name":"北京西","train_class_name":"高速","service_type":"1","start_time":"16:53","stopover_time":"----","end_station_name":"郑州东","station_no":"01","isEnabled":true},{"arrive_time":"17:34","station_name":"保定东","start_time":"17:36","stopover_time":"2分钟","station_no":"02","isEnabled":true},{"arrive_time":"18:12","station_name":"石家庄","start_time":"18:15","stopover_time":"3分钟","station_no":"03","isEnabled":true},{"arrive_time":"18:45","station_name":"邢台东","start_time":"18:47","stopover_time":"2分钟","station_no":"04","isEnabled":false},{"arrive_time":"19:04","station_name":"邯郸东","start_time":"19:06","stopover_time":"2分钟","station_no":"05","isEnabled":false},{"arrive_time":"19:23","station_name":"安阳东","start_time":"19:25","stopover_time":"2分钟","station_no":"06","isEnabled":false},{"arrive_time":"19:51","station_name":"新乡东","start_time":"19:53","stopover_time":"2分钟","station_no":"07","isEnabled":false},{"arrive_time":"20:14","station_name":"郑州东","start_time":"20:14","stopover_time":"----","station_no":"08","isEnabled":false}]},"messages":[],"validateMessages":{}}

**Comment by miaomiaokang** [comment]
可以了，是res出错了。
